# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/GenPyTorch.jl

language: julia

os:
    - linux

julia:
  - 1.3

env:
    - PYTHON=/home/travis/build/probcomp/GenPyTorch.jl/pytorch_env/bin/python3

jobs:
  include:
    - stage: test
      before_install:
        - sudo ./install_pytorch.sh
      script:
        - julia -e 'using Pkg; Pkg.build("PyCall"); Pkg.test()'
    - stage: docs
      julia: 1.3
      os: linux
      before_install:
        - sudo ./install_pytorch.sh
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.add(PackageSpec(url="https://github.com/probcomp/Gen"));
                                    Pkg.develop(PackageSpec(path="$(pwd())/.."));
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.add("PyCall");
                                    Pkg.build("PyCall");
                                    using PyCall;
                                    println(ENV["PYTHON"]);
                                    println(PyCall.python)'
        - julia --project=docs/ docs/make.jl
      after_success: skip
